name = "nur-packages"

packages = [
  "cargo",
  "gcc",
  "niv",
  "nix-prefetch",
  "nix-prefetch-github",
  "nix-update",
  "pre-commit",
  "shellcheck",
]

[env]
PRE_COMMIT_COLOR = "never"
SHELLCHECK_OPTS = "-e SC1008"
