name: Update sources

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Nix
      uses: cachix/install-nix-action@v11
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Checkout
      uses: actions/checkout@v2.3.3

    - name: Prevent garbage collections of gcroots
      run:
        printf "keep-outputs = true\nkeep-derivations = true\n" | sudo tee -a /etc/nix/nix.conf;

    - name: Restart nix-daemon with systemctl
      run:
        sudo systemctl restart nix-daemon

    - name: Run tests
      run: nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/nixpkgs-unstable.tar.gz test.nix --run 'true'
