name: Update sources

on:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install nix
      uses: cachix/install-nix-action@v11
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Checkout repository
      uses: actions/checkout@v2.3.3

    - name: Setup cachix
      uses: cachix/cachix-action@v6
      with:
        name: reedrw
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'


    - name: Setup nix-shell
      run: nix-shell shell.nix --run 'exit'

    - name: Update packages
      run: ./update.sh

    - name: Commit and push
      uses: EndBug/add-and-commit@v5
      with:
        author_name: GitHub Action
        author_email: action@github.com
        message: "automated update"
        add: "--all"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Update NUR
      run: curl -XPOST https://nur-update.herokuapp.com/update?repo=reedrw
