name: Update sources

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Nix
      uses: cachix/install-nix-action@v11
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Checkout
      uses: actions/checkout@v2.3.3

    - name: Update packages
      run: ./update.sh

    - name: Commit and Push
      uses: EndBug/add-and-commit@v5
      with:
        author_name: GitHub Action
        author_email: action@github.com
        message: "automated update"
        add: "--all"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Update NUR
      run: curl -XPOST https://nur-update.herokuapp.com/update?repo=reedrw
